apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-mongo-service-monitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: spring-boot
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"