apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"  
    spec:
      containers:
      - name: spring-mongo-container
        image: haythemkaouech/spring-mongo:prom
        ports:
        - containerPort: 8080
        

---

apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  namespace: default
spec:
  selector:
    app: spring-boot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http-port
  type: LoadBalancer
